# Generated by Django 3.0 on 2021-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField(unique=True)),
            ],
        ),
    ]
